[package]
name = "mbtileserver"
version = "0.1.0"
authors = ["kaveh <kaveh@illinois.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
hyper = "0.12"
libsqlite3-sys = "0.16"
pretty_env_logger = "0.3"
rusqlite = "0.20"
